<#
    Builds "Riverbreak" - a 1v1, 512 m, tropical map.

    Serpent Crossing's skeleton (corner-to-corner river, two causeways, bases
    back from opposite banks) with two things replaced:

      * the river is a 1-D noise meander of varying width rather than a sine,
        so it wanders like a river instead of tracing a wave
      * the organic mesa field is laid over the rolling ground, suppressed near
        the channel, the base pads and the bridge approaches

    Everything is placed in river-relative coordinates (t along the diagonal,
    signed metres from the actual centreline), so the layout keeps its
    clearances no matter where the meander happens to go. CarveRamps then
    guarantees the hills are climbable, and it is forbidden from touching the
    channel so it can never hand out a free crossing.
#>
[CmdletBinding()]
param(
    [string]$MapsRoot = 'F:\SteamLibrary\steamapps\common\Sanctuary Shattered Sun Demo\engine\Sanctuary_Data\Maps',
    [string]$Folder   = 'Riverbreak',
    [string]$MapName  = 'Riverbreak',
    [ValidateSet('.santp', '.sanprop')]
    [string]$PropExtension = '.santp',
    [int]$Size = 512,
    [string]$DebugOut,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
. (Join-Path $here 'src' 'Import-MapGen.ps1')
. (Join-Path $here 'src' 'Biomes.ps1')

$mapDir = Join-Path $MapsRoot $Folder
$texDir = Join-Path $mapDir 'Textures'
if (Test-Path $mapDir) {
    if (-not $Force) { throw "'$mapDir' exists. Pass -Force." }
    Remove-Item $mapDir -Recurse -Force
}
$null = New-Item -ItemType Directory -Path $texDir -Force

# ------------------------------------------------------------- config ----

$M = [double]$Size
[MapGen]::Configure([float]$Size, $(if ($Size -ge 512) { 1024 } else { 512 }))
[MapGen]::UseRiver     = $true
[MapGen]::Organic      = $false
[MapGen]::OrganicRiver = $true
[MapGen]::OrganicHills = $true
[MapGen]::HillStrength = 1.0
[MapGen]::CurveAmp         = 44.0
[MapGen]::MesaScale        = 0.155
[MapGen]::MesaThreshold    = 0.665   # higher = fewer, more deliberate massifs
[MapGen]::ErosionStrength  = 0.055   # bites bays out of the outlines
[MapGen]::MesaTier1Height  = 12.0
[MapGen]::MesaTier2Height  = 8.0
[MapGen]::OutcropHeight    = 0.0     # no scattered buttes: pure clutter for pathing

# Bases 62 m off the centreline, 27% along the diagonal. Derived from the real
# meander rather than hardcoded, so the clearance holds however it wanders.
[MapGen]::ComputeBridgePositions()
[MapGen]::PlaceBases(0.27, 62.0)

$bx0 = [MapGen]::BaseX[0]; $bz0 = [MapGen]::BaseZ[0]
"Bases: ({0:N0},{1:N0}) and ({2:N0},{3:N0})" -f $bx0, $bz0, [MapGen]::BaseX[1], [MapGen]::BaseZ[1] | Write-Host
"Bridges: ({0:N0},{1:N0}) and ({2:N0},{3:N0})" -f `
    [MapGen]::BridgeX[0], [MapGen]::BridgeZ[0], [MapGen]::BridgeX[1], [MapGen]::BridgeZ[1] | Write-Host

Write-Host "Building heightfield ($Size m, meandering river + organic hills)..."
[MapGen]::BuildHeight()

# ------------------------------------------------------- ramp carving ----

Write-Host 'Carving ramps...'
[MapGen]::BuildWalkable()
$walk0  = [MapGen]::WalkableCount()
$before = [MapGen]::CountTrue([MapGen]::Reachable($bx0, $bz0))
"  before: {0:P0} of walkable ground reachable from ARMY_1" -f ($before / $walk0) | Write-Host
$carved = [MapGen]::CarveRamps($bx0, $bz0, 40, 11.0, 9.0, 120)
# Sand off invisible one-cell obstacles: they leave the map 100% reachable
# but litter it with pinch points units path around.
$despeckled = [MapGen]::SmoothPathingSpecks(60, 8)
"  smoothed {0} isolated blocked patches" -f $despeckled | Write-Host
"  cut {0} ramp corridor(s)" -f $carved | Write-Host

[MapGen]::BuildWalkable()
$reach = [MapGen]::Reachable($bx0, $bz0)
$walk  = [MapGen]::WalkableCount()
$rc    = [MapGen]::CountTrue($reach)
"  after:  {0:P0} of walkable ground reachable ({1:N0} / {2:N0})" -f ($rc/$walk), $rc, $walk | Write-Host

Write-Host 'Building stratum weights...'
[MapGen]::BuildLayers()
# Slot badges on the preview, in spawn order.
[MapGen]::PreviewSpawnX = [float[]][MapGen]::BaseX.Clone()
[MapGen]::PreviewSpawnZ = [float[]][MapGen]::BaseZ.Clone()

# ------------------------------------------------------------ markers ----

# Alloys in river-relative coordinates: (t along the diagonal, metres from the
# centreline). Positive perp is the top-left player's bank; the mirror set is
# generated by (1-t, -perp), which is exactly the 180-degree rotation.
#
# Bank room runs out near the corners: at t, the top edge caps perp at about
# (Size - 10 - Size*(1-t)) / 0.7071, so a large offset at low t lands off the
# map. These are all inside that.
$alloySideA = @(
    @(0.20, 50),  @(0.24, 88),  @(0.33, 58),  @(0.31, 118),
    @(0.15, 48),  @(0.40, 92),  @(0.46, 148), @(0.55, 62),
    @(0.50, 44)
)

$spawns = @(
    @{ Army = 'ARMY_1'; X = [double][MapGen]::BaseX[0]; Z = [double][MapGen]::BaseZ[0] }
    @{ Army = 'ARMY_2'; X = [double][MapGen]::BaseX[1]; Z = [double][MapGen]::BaseZ[1] }
)

function Test-Ok {
    param([double]$X, [double]$Z, [double]$MaxSlope, [double]$MinRiver)
    if ($X -lt 10 -or $X -gt ($M - 10) -or $Z -lt 10 -or $Z -gt ($M - 10)) { return $false }
    if ([MapGen]::HeightAtWorld($X, $Z) -le ([MapGen]::WaterLevel + 1.0)) { return $false }
    if ([MapGen]::SlopeAtWorld($X, $Z) -gt $MaxSlope) { return $false }
    if ([math]::Abs([MapGen]::RiverDist($X, $Z)) -lt $MinRiver) { return $false }
    [MapGen]::IsReachable($reach, $X, $Z)
}

function Resolve-Spot {
    param([double]$X, [double]$Z, [double]$MaxSlope, [double]$MinRiver, [string]$Label)
    if (Test-Ok $X $Z $MaxSlope $MinRiver) { return ,@($X, $Z) }
    foreach ($rad in 5, 10, 15, 21, 28, 36, 45) {
        foreach ($deg in 0..23) {
            $a = $deg * 15 * [math]::PI / 180
            $nx = [math]::Round($X + $rad * [math]::Cos($a))
            $nz = [math]::Round($Z + $rad * [math]::Sin($a))
            if (Test-Ok $nx $nz $MaxSlope $MinRiver) {
                Write-Host ("  nudged {0}: ({1:N0},{2:N0}) -> ({3},{4})  [{5} m]" -f $Label, $X, $Z, $nx, $nz, $rad)
                return ,@([double]$nx, [double]$nz)
            }
        }
    }
    Write-Warning "could not place $Label"
    return ,@($X, $Z)
}

Write-Host 'Placing markers...'
$resolvedA = @()
$i = 0
foreach ($rp in $alloySideA) {
    $i++
    $t = [float]$rp[0]
    $perp = [float]$rp[1]
    $wx = 0.0; $wz = 0.0
    [MapGen]::RiverToWorld($t, $perp, [ref]$wx, [ref]$wz)
    $resolvedA += ,(Resolve-Spot ([double]$wx) ([double]$wz) 12.0 34.0 ("alloy A{0}" -f $i))
}

$alloyPts = @()
foreach ($p in $resolvedA) { $alloyPts += ,@([double]$p[0], [double]$p[1]) }
foreach ($p in $resolvedA) {
    $rx = $M - [double]$p[0]
    $rz = $M - [double]$p[1]
    $alloyPts += ,@($rx, $rz)
}

# --------------------------------------------------------- validation ---

Write-Host 'Pathability (Land layer, maxSlope 30 deg):'
$enemyOk = [MapGen]::IsReachable($reach, [MapGen]::BaseX[1], [MapGen]::BaseZ[1])
"  enemy spawn reachable overland: {0}" -f $(if($enemyOk){'YES'}else{'NO - the bridges do not connect!'}) | Write-Host
$bad = @(); $i = 0
foreach ($p in $alloyPts) {
    $i++
    if (-not [MapGen]::IsReachable($reach, $p[0], $p[1])) { $bad += ("Alloys_{0:D3}" -f $i) }
}
if ($bad.Count) { Write-Warning ("  cut off: {0}" -f ($bad -join ', ')) }
else { Write-Host ("  all {0} alloy spots reachable on foot" -f $alloyPts.Count) }
for ($b = 0; $b -lt 2; $b++) {
    $ok = [MapGen]::IsReachable($reach, [MapGen]::BridgeX[$b], [MapGen]::BridgeZ[$b])
    "  bridge {0} deck reachable: {1}" -f ($b+1), $(if($ok){'YES'}else{'NO'}) | Write-Host
}

Write-Host 'Crossings:'
for ($b = 0; $b -lt 2; $b++) {
    $prof = [MapGen]::CrossingProfile($b, 161)
    $min  = ($prof | Measure-Object -Minimum).Minimum
    $state = if ($min -gt [MapGen]::WaterLevel) { 'CONTINUOUS dry land' } else { 'BROKEN' }
    "  bridge {0}: lowest point {1:N2} m (water {2:N1} m) -> {3}" -f ($b+1), $min, [MapGen]::WaterLevel, $state | Write-Host
}
$riverMax = [MapGen]::RiverMaxHeightBetweenBridges()
"  river elsewhere: highest bed point {0:N2} m -> {1}" -f $riverMax, `
    $(if($riverMax -lt [MapGen]::WaterLevel){'sealed'}else{'LEAKS'}) | Write-Host

$ts = [MapGen]::TerrainStats(); $land = $ts[2]
"Terrain: {0:N1} m .. {1:N2} m ({2:N1} m of relief)" -f $ts[0], $ts[1], ($ts[1]-$ts[0]) | Write-Host
"  slopes: {0:P0} flat (<6), {1:P0} gentle (6-15), {2:P0} steep (15-34), {3:P0} cliff (>34)" -f `
    ($ts[3]/$land), ($ts[4]/$land), ($ts[5]/$land), ($ts[6]/$land) | Write-Host

$og = [MapGen]::OpenGroundStats(6.0)
"  open ground: largest contiguous level area is {0:P0} of the land, {1:N0} separate areas over 400 cells" -f ($og[0]/$og[1]), $og[2] | Write-Host
Write-Host ''

# ---------------------------------------------------------- textures ----

Write-Host 'Writing textures...'
[MapGen]::WriteHeightmap((Join-Path $texDir 'heightmap.raw'))
[MapGen]::WriteStratums($texDir)
[MapGen]::WriteTints($texDir, 2048)
[MapGen]::WritePreview((Join-Path $texDir 'preview.png'), 512, $false, $null, $null, $null)
Copy-Item (Join-Path $texDir 'preview.png') (Join-Path $mapDir 'preview.png')

# -------------------------------------------------------------- props ---

$treeBps = @('edbm0121','edbm0122','edbm0123','edbm0124','edbm0125')
$rockBps = @('edmm0104','edmm0106','edms0110')
$avoidX = [float[]]($alloyPts | ForEach-Object { [float]$_[0] })
$avoidZ = [float[]]($alloyPts | ForEach-Object { [float]$_[1] })

Write-Host "Scattering props ($PropExtension)..."
$buckets = @{}
foreach ($b in ($treeBps + $rockBps)) { $buckets[$b] = @() }
foreach ($set in @(
        @{ Bps = $treeBps; Rocks = $false; Count = 340; Seed = 8081 },
        @{ Bps = $rockBps; Rocks = $true;  Count = 130; Seed = 4409 })) {
    $flat = [MapGen]::Scatter($set.Seed, $set.Count, $set.Rocks, $avoidX, $avoidZ, 13.0)
    $n = $flat.Length / 5
    for ($k = 0; $k -lt $n; $k++) {
        $x = [double]$flat[$k*5]; $y = [double]$flat[$k*5+1]; $z = [double]$flat[$k*5+2]
        $yaw = [double]$flat[$k*5+3]; $sc = [double]$flat[$k*5+4]
        $bp = $set.Bps[$k % $set.Bps.Count]
        foreach ($inst in @(@($x, $z, $yaw), @(($M - $x), ($M - $z), ($yaw + [math]::PI)))) {
            $buckets[$bp] += ,[ordered]@{
                position = @{ x = [math]::Round($inst[0],3); y = [math]::Round($y,3); z = [math]::Round($inst[1],3) }
                rotation = @{ x = 0.0; y = [math]::Round([math]::Sin($inst[2]/2),7); z = 0.0; w = [math]::Round([math]::Cos($inst[2]/2),7) }
                scale    = @{ x = [math]::Round($sc,4); y = [math]::Round($sc,4); z = [math]::Round($sc,4) }
            }
        }
    }
    Write-Host ("  {0}: {1} per bank -> {2} total" -f $(if($set.Rocks){'rocks'}else{'trees'}), $n, ($n*2))
}
$propGroups = @()
foreach ($b in ($treeBps + $rockBps)) {
    if ($buckets[$b].Count -eq 0) { continue }
    $propGroups += ,[ordered]@{
        blueprintPath = "Environment/01_Highlands/Props/$b/$b$PropExtension"
        transforms    = $buckets[$b]
    }
}

if ($DebugOut) {
    $mx = @(); $mz = @(); $mk = @()
    foreach ($g in $propGroups) { foreach ($t in $g.transforms) { $mx += [float]$t.position.x; $mz += [float]$t.position.z; $mk += 2 } }
    foreach ($p in $alloyPts) { $mx += [float]$p[0]; $mz += [float]$p[1]; $mk += 1 }
    foreach ($s in $spawns)   { $mx += [float]$s.X;  $mz += [float]$s.Z;  $mk += 0 }
    [MapGen]::WritePreview($DebugOut, 900, $true, [float[]]$mx, [float[]]$mz, [int[]]$mk)
    $stem = [IO.Path]::ChangeExtension($DebugOut, $null).TrimEnd('.')
    [MapGen]::WriteHeightPreview("${stem}_elevation.png", 900)
    [MapGen]::WriteWalkPreview("${stem}_walk.png", 900, $reach)
    Write-Host "  renders -> $DebugOut, ${stem}_elevation.png, ${stem}_walk.png"
}

# -------------------------------------------------------------- json ----

function S {
    param([string]$Tex, [double]$Tile, [double]$Far, [double]$Tri, [double]$TriFar,
          [double]$Nrm, [double]$NrmFar, [double]$NB, [double]$HB,
          [double[]]$Diff, [double[]]$FarRemap, [double[]]$MMin, [double[]]$MMax)
    $p = "Environment/01_Highlands/Stratum/$Tex"
    [ordered]@{
        name = $null
        albedo = @{ path = "${p}_albedo.tga" }
        normal = @{ path = "${p}_normal.tga" }
        mask   = @{ path = "${p}_mask.tga" }
        tileSize             = @{ x = $Tile; y = $Tile }
        tileSizeFar          = @{ x = $Far;  y = $Far }
        tileSizeTriplanar    = $Tri
        tileSizeFarTriplanar = $TriFar
        normalScale        = $Nrm
        normalScaleFar     = $NrmFar
        normalFarNearBlend = $NB
        heightFarNearBlend = $HB
        diffuseRemap  = @{ r = $Diff[0];     g = $Diff[1];     b = $Diff[2];     a = $Diff[3] }
        farColorRemap = @{ r = $FarRemap[0]; g = $FarRemap[1]; b = $FarRemap[2]; a = $FarRemap[3] }
        maskRemapMin  = @{ x = $MMin[0]; y = $MMin[1]; z = $MMin[2]; w = $MMin[3] }
        maskRemapMax  = @{ x = $MMax[0]; y = $MMax[1]; z = $MMax[2]; w = $MMax[3] }
    }
}

$g07 = @{ D = @(0.309759647,0.319,0.268598,1.0); F = @(0.0159015749,0.007912427,0.004240413,0.0) }
$stratums = @(
    (S 'highlands_100m_grass07'      10 64 12 36 1.0 1.22 0.0   0.5 $g07.D $g07.F @(0,0,0.1,0) @(1,1,0.9,1))
    (S 'highlands_60m_rock_basalt01' 10 44 10 36 1.0 1.0  0.2   0.5 @(0.58,0.556,0.54,1.0)     @(1,1,1,0) @(0,0,0,0) @(1,1,1,1))
    (S 'highlands_100m_heather03'     8 32 12 36 1.0 1.0  0.5   0.5 @(0.298,0.286,0.192,1.0)   @(0.0376,0.0347,0.0347,0.0) @(0,0,0,0) @(1,1,1,1))
    (S 'highlands_100m_grass02'       8 64 12 36 1.0 1.0  0.319 0.5 @(0.549,0.584,0.541,1.0)   @(0.2355,0.2004,0.148,0.0) @(0,0,0,0) @(1,1,1,1))
    (S 'highlands_100m_grass03'       8 32 12 36 1.0 1.0  0.534 0.5 @(0.528,0.615,0.702,1.0)   @(0.0659,0.0435,0.0224,0.0) @(0,0,0.1,0) @(1,1,0.8,1))
    (S 'highlands_100m_mud02'         8 40 12 36 1.0 1.0  0.566 0.5 @(0.528,0.615,0.702,1.0)   @(1,1,1,0) @(0,0,0,0) @(1,1,1,1))
    (S 'highlands_100m_sand02'       10 32  8 36 0.8 0.8  0.062 0.5 @(0.263,0.204,0.110,1.0)   @(0.2506,0.2134,0.1388,0.0) @(0,0,0,0) @(1,1,1,1))
    (S 'highlands_100m_rock_cliff01' 12 52 10 36 1.0 1.0  0.164 0.5 @(0.6667,0.5373,0.5137,1.0) @(1,1,1,0) @(0,0,0,0) @(1,1,1,1))
    (S 'highlands_60m_gravel01'      12 52 10 36 1.0 1.0  0.164 0.5 @(0.62,0.58,0.53,1.0)      @(1,1,1,0) @(0,0,0,0) @(1,1,1,1))
)

function T {
    param([double]$X, [double]$Y, [double]$Z)
    [ordered]@{
        position = @{ x = $X;  y = $Y;  z = $Z }
        rotation = @{ x = 0.0; y = 0.0; z = 0.0; w = 1.0 }
        scale    = @{ x = 1.0; y = 1.0; z = 1.0 }
    }
}

$spawnT = [ordered]@{}
foreach ($s in $spawns) { $spawnT[$s.Army] = T $s.X ([math]::Round([MapGen]::HeightAtWorld($s.X, $s.Z), 2)) $s.Z }

$alloyT = [ordered]@{}
$i = 0
foreach ($p in $alloyPts) {
    $i++
    $y = [math]::Round([MapGen]::HeightAtWorld($p[0], $p[1]), 2)
    $alloyT["Alloys_{0:D3}" -f $i] = T $p[0] $y $p[1]
}

function Army { [ordered]@{ faction = 0; alloys = 500.0; energy = 500.0; groups = @{} } }

$map = [ordered]@{
    fileVersion         = 3
    mapVersion          = 1
    name                = $MapName
    credits             = ''
    width               = $Size
    length              = $Size
    height              = 128
    heightmapResolution = [MapGen]::HRes
    hasWater                   = $true
    waterLevel                 = [double][MapGen]::WaterLevel
    waterDepth                 = 2.0
    waterWindSpeed             = 0.06
    waterWindDirection         = 100.0
    waterShoreDepthOffset      = 8.0
    waterShoreDepthStrength    = 0.7
    waterShoreDistanceOffset   = 0.0
    waterShoreDistanceStrength = 2.0
    shader              = 'RTS/TerrainLit'
    heightTransition    = 2.0
    fadeDistance        = 55.0
    fadeStartDistance   = 32.0
    stratumLayers       = $stratums

    sunRA                     = 96.2
    sunDA                     = 32.0
    sunIntensity              = 60000.0
    sunTint                   = @{ r = 1.0; g = 1.0; b = 1.0; a = 1.0 }
    sunTemperature            = 9200.0
    sunAngularDiameter        = 0.5
    sunVolumetricsMultiplier  = 6.7
    sunVolumetricsShadowDimer = 0.5
    skylightIntensity         = 0.0
    skylightTint              = @{ r = 1.0; g = 1.0; b = 1.0; a = 1.0 }
    skylightTemperature       = 12000.0
    exposure                  = 11.5
    exposureCompensation      = 0.0
    skyboxExposure            = 12.0
    fogAttenuationDistance    = 330.0
    fogBaseHeight             = 5.41
    fogMaximumHeight          = 140.0
    fogMaximumDistance        = 1800.0
    fogAnisotropy             = 0.0
    skybox = @{ path = 'Environment/Skybox/kloofendal_48d_partly_cloudy_puresky_4k.exr' }

    areas   = @{ Playable = @{ x = 0.0; y = 0.0; width = [double]$Size; height = [double]$Size } }
    armies  = [ordered]@{ ARMY_1 = (Army); ARMY_2 = (Army) }
    chains  = @{}
    markers = [ordered]@{
        Spawn  = [ordered]@{ resource = $false; transforms = $spawnT }
        Alloys = [ordered]@{ resource = $true;  transforms = $alloyT }
    }
    decals = @()
    windSpeed     = 0.25
    windDirection = 160.0
    props         = $propGroups
}

# Fields the shipped maps set that SanMap would otherwise default badly - most
# importantly the height fog. See src\Biomes.ps1.
foreach ($kv in (New-MapEnvironment 'Tropical' ([double][MapGen]::WaterLevel)).GetEnumerator()) {
    $map[$kv.Key] = $kv.Value
}
$sanmap = Join-Path $mapDir "$Folder.sanmap"
[IO.File]::WriteAllText($sanmap, ($map | ConvertTo-Json -Depth 12), (New-Object Text.UTF8Encoding $false))

Write-Host ''
& (Join-Path $MapGenTools 'Test-Sanmap.ps1') -Path $sanmap -CheckTextures
Write-Host ''
Write-Host "Open: $sanmap"
