<#
    Builds "Broken Mesa" - a 1v1, 512 m, dry highland map.

    Where Serpent Crossing uses analytic plateaus, this thresholds a
    domain-warped noise field into branching mesas: organic outlines, flat tops,
    hard cliff edges, and a second tier nested inside the first. Nothing about
    that construction produces a way up, so CarveRamps finds every stranded
    region and cuts a constant-gradient corridor down to reachable ground,
    repeating until the whole map is connected.

    No river - the barriers here are the cliffs themselves.
#>
[CmdletBinding()]
param(
    [string]$MapsRoot = 'F:\SteamLibrary\steamapps\common\Sanctuary Shattered Sun Demo\engine\Sanctuary_Data\Maps',
    [string]$Folder   = 'Broken_Mesa',
    [string]$MapName  = 'Broken Mesa',
    [ValidateSet('.santp', '.sanprop')]
    [string]$PropExtension = '.santp',
    [int]$Size = 512,
    [int]$Seed = 20250822,
    [string]$DebugOut,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
. (Join-Path $here 'src' 'Import-MapGen.ps1')
. (Join-Path $here 'src' 'Biomes.ps1')

$mapDir = Join-Path $MapsRoot $Folder
$texDir = Join-Path $mapDir 'Textures'
if (Test-Path $mapDir) {
    if (-not $Force) { throw "'$mapDir' exists. Pass -Force." }
    Remove-Item $mapDir -Recurse -Force
}
$null = New-Item -ItemType Directory -Path $texDir -Force

# ------------------------------------------------------------- config ----

$M = [double]$Size
[MapGen]::Configure([float]$Size, $(if ($Size -ge 512) { 1024 } else { 512 }))
[MapGen]::UseRiver     = $false
[MapGen]::Organic      = $false
[MapGen]::OrganicHills = $false
[MapGen]::PathedMesas  = $true
[MapGen]::LandBase     = 22.0
[MapGen]::WaterLevel   = 0.0      # dry map; nothing sits below this
[MapGen]::HillStrength = 1.0

# Nothing but mesa country here, so it wants more landforms than Cleftwater and
# can afford a smaller centre keep-out with no river splitting the middle.
[MapGen]::MesaPathCount   = 8
[MapGen]::MesaMinSep      = 0.155
[MapGen]::MesaCentreClear = 0.15
[MapGen]::MesaInflate     = 0.015
[MapGen]::MesaRampCount   = 7
[MapGen]::MesaRampWidth   = 15.0
[MapGen]::OutcropHeight   = 0.0

# Spawns on the TL/BR diagonal, pulled in from the corners.
# Each element is parenthesised because PowerShell's comma binds tighter than
# '*', so @( $Size * 0.22, $Size * 0.78 ) parses as $Size * (0.22,$Size) * 0.78.
[MapGen]::BaseX = [float[]]@( ($Size * 0.22), ($Size * 0.78) )
[MapGen]::BaseZ = [float[]]@( ($Size * 0.78), ($Size * 0.22) )

Write-Host 'Building mesa masks (paths -> inflate -> quarter-res -> dilute -> blur -> distance field)...'
[MapGen]::BuildMesaField($Seed, 15.0, 10.0)

Write-Host "Building heightfield ($Size m, pathed mesas)..."
[MapGen]::BuildHeight()

# ------------------------------------------------------- ramp carving ----

Write-Host 'Carving ramps...'
[MapGen]::BuildWalkable()
$before = [MapGen]::CountTrue([MapGen]::Reachable([MapGen]::BaseX[0], [MapGen]::BaseZ[0]))
$walk0  = [MapGen]::WalkableCount()
"  before: {0:P0} of walkable ground reachable from ARMY_1" -f ($before / $walk0) | Write-Host

$carved = [MapGen]::CarveRamps([MapGen]::BaseX[0], [MapGen]::BaseZ[0], 40, 11.0, 9.0, 120)
# Sand off invisible one-cell obstacles: they leave the map 100% reachable
# but litter it with pinch points units path around.
$despeckled = [MapGen]::SmoothPathingSpecks(60, 8)
"  smoothed {0} isolated blocked patches" -f $despeckled | Write-Host
"  cut {0} ramp corridor(s)" -f $carved | Write-Host

[MapGen]::BuildWalkable()
$reach = [MapGen]::Reachable([MapGen]::BaseX[0], [MapGen]::BaseZ[0])
$walk  = [MapGen]::WalkableCount()
$rc    = [MapGen]::CountTrue($reach)
"  after:  {0:P0} of walkable ground reachable ({1:N0} / {2:N0} cells)" -f ($rc/$walk), $rc, $walk | Write-Host

Write-Host 'Building stratum weights...'
[MapGen]::BuildLayers()

# ------------------------------------------------------------ markers ----

# Nine per side; the mirror set is generated by rotation so the map is fair.
# Positions are fractions of map size so this scales with -Size.
$alloyFracA = @(
    @(0.22,0.90), @(0.31,0.86), @(0.14,0.74), @(0.30,0.70),
    @(0.44,0.92), @(0.09,0.55), @(0.47,0.72), @(0.62,0.88),
    @(0.40,0.55)
)

$spawns = @(
    @{ Army = 'ARMY_1'; X = [double][MapGen]::BaseX[0]; Z = [double][MapGen]::BaseZ[0] }
    @{ Army = 'ARMY_2'; X = [double][MapGen]::BaseX[1]; Z = [double][MapGen]::BaseZ[1] }
)

function Test-Ok {
    param([double]$X, [double]$Z, [double]$MaxSlope)
    if ($X -lt 10 -or $X -gt ($M - 10) -or $Z -lt 10 -or $Z -gt ($M - 10)) { return $false }
    if ([MapGen]::SlopeAtWorld($X, $Z) -gt $MaxSlope) { return $false }
    # must also be somewhere units can actually stand
    [MapGen]::IsReachable($reach, $X, $Z)
}

function Resolve-Spot {
    param([double]$X, [double]$Z, [double]$MaxSlope, [string]$Label)
    if (Test-Ok $X $Z $MaxSlope) { return ,@($X, $Z) }
    foreach ($rad in 5, 10, 15, 21, 28, 36, 45, 55) {
        foreach ($deg in 0..23) {
            $a = $deg * 15 * [math]::PI / 180
            $nx = [math]::Round($X + $rad * [math]::Cos($a))
            $nz = [math]::Round($Z + $rad * [math]::Sin($a))
            if (Test-Ok $nx $nz $MaxSlope) {
                Write-Host ("  nudged {0}: ({1},{2}) -> ({3},{4})  [{5} m]" -f $Label, $X, $Z, $nx, $nz, $rad)
                return ,@([double]$nx, [double]$nz)
            }
        }
    }
    Write-Warning "could not place $Label near ($X,$Z)"
    return ,@($X, $Z)
}

Write-Host 'Placing markers...'
$resolvedA = @()
$i = 0
foreach ($f in $alloyFracA) {
    $i++
    # Locals on purpose: PowerShell mis-parses `[double]$f[0] * $M`.
    $fx = [double]$f[0]
    $fz = [double]$f[1]
    $resolvedA += ,(Resolve-Spot ($fx * $M) ($fz * $M) 12.0 ("alloy A{0}" -f $i))
}

$alloyPts = @()
foreach ($p in $resolvedA) { $alloyPts += ,@([double]$p[0], [double]$p[1]) }
foreach ($p in $resolvedA) {
    $rx = $M - [double]$p[0]
    $rz = $M - [double]$p[1]
    $alloyPts += ,@($rx, $rz)
}

# --------------------------------------------------------- validation ---

Write-Host 'Pathability (Land layer, maxSlope 30 deg):'
$enemyOk = [MapGen]::IsReachable($reach, [MapGen]::BaseX[1], [MapGen]::BaseZ[1])
"  enemy spawn reachable overland: {0}" -f $(if($enemyOk){'YES'}else{'NO'}) | Write-Host
$bad = @()
$i = 0
foreach ($p in $alloyPts) {
    $i++
    if (-not [MapGen]::IsReachable($reach, $p[0], $p[1])) { $bad += ("Alloys_{0:D3}" -f $i) }
}
if ($bad.Count) { Write-Warning ("  cut off: {0}" -f ($bad -join ', ')) }
else { Write-Host ("  all {0} alloy spots reachable on foot" -f $alloyPts.Count) }

$ts = [MapGen]::TerrainStats()
$land = $ts[2]
"Terrain: {0:N1} m .. {1:N2} m ({2:N1} m of relief)" -f $ts[0], $ts[1], ($ts[1] - $ts[0]) | Write-Host
"  slopes: {0:P0} flat (<6 deg), {1:P0} gentle (6-15), {2:P0} steep (15-34), {3:P0} cliff (>34)" -f `
    ($ts[3]/$land), ($ts[4]/$land), ($ts[5]/$land), ($ts[6]/$land) | Write-Host
Write-Host ''

# ---------------------------------------------------------- textures ----

Write-Host 'Writing textures...'
[MapGen]::WriteHeightmap((Join-Path $texDir 'heightmap.raw'))
[MapGen]::WriteStratums($texDir)
[MapGen]::WriteTints($texDir, 2048)
[MapGen]::WritePreview((Join-Path $texDir 'preview.png'), 512, $false, $null, $null, $null)
Copy-Item (Join-Path $texDir 'preview.png') (Join-Path $mapDir 'preview.png')

# -------------------------------------------------------------- props ---

$treeBps = @('edbm0121','edbm0122','edbm0123','edbm0124','edbm0125')
$rockBps = @('edmm0104','edmm0106','edms0110')
$avoidX = [float[]]($alloyPts | ForEach-Object { [float]$_[0] })
$avoidZ = [float[]]($alloyPts | ForEach-Object { [float]$_[1] })

Write-Host "Scattering props ($PropExtension)..."
$buckets = @{}
foreach ($b in ($treeBps + $rockBps)) { $buckets[$b] = @() }
foreach ($set in @(
        @{ Bps = $treeBps; Rocks = $false; Count = 420; Seed = 2207 },
        @{ Bps = $rockBps; Rocks = $true;  Count = 180; Seed = 9311 })) {
    $flat = [MapGen]::Scatter($set.Seed, $set.Count, $set.Rocks, $avoidX, $avoidZ, 14.0)
    $n = $flat.Length / 5
    for ($k = 0; $k -lt $n; $k++) {
        $x = [double]$flat[$k*5]; $y = [double]$flat[$k*5+1]; $z = [double]$flat[$k*5+2]
        $yaw = [double]$flat[$k*5+3]; $sc = [double]$flat[$k*5+4]
        $bp = $set.Bps[$k % $set.Bps.Count]
        foreach ($inst in @(@($x, $z, $yaw), @(($M - $x), ($M - $z), ($yaw + [math]::PI)))) {
            $buckets[$bp] += ,[ordered]@{
                position = @{ x = [math]::Round($inst[0],3); y = [math]::Round($y,3); z = [math]::Round($inst[1],3) }
                rotation = @{ x = 0.0; y = [math]::Round([math]::Sin($inst[2]/2),7); z = 0.0; w = [math]::Round([math]::Cos($inst[2]/2),7) }
                scale    = @{ x = [math]::Round($sc,4); y = [math]::Round($sc,4); z = [math]::Round($sc,4) }
            }
        }
    }
    Write-Host ("  {0}: {1} per side -> {2} total" -f $(if($set.Rocks){'rocks'}else{'trees'}), $n, ($n*2))
}
$propGroups = @()
foreach ($b in ($treeBps + $rockBps)) {
    if ($buckets[$b].Count -eq 0) { continue }
    $propGroups += ,[ordered]@{
        blueprintPath = "Environment/01_Highlands/Props/$b/$b$PropExtension"
        transforms    = $buckets[$b]
    }
}

if ($DebugOut) {
    $mx = @(); $mz = @(); $mk = @()
    foreach ($g in $propGroups) { foreach ($t in $g.transforms) { $mx += [float]$t.position.x; $mz += [float]$t.position.z; $mk += 2 } }
    foreach ($p in $alloyPts) { $mx += [float]$p[0]; $mz += [float]$p[1]; $mk += 1 }
    foreach ($s in $spawns)   { $mx += [float]$s.X;  $mz += [float]$s.Z;  $mk += 0 }
    [MapGen]::WritePreview($DebugOut, 900, $true, [float[]]$mx, [float[]]$mz, [int[]]$mk)
    $stem = [IO.Path]::ChangeExtension($DebugOut, $null).TrimEnd('.')
    [MapGen]::WriteHeightPreview("${stem}_elevation.png", 900)
    [MapGen]::WriteWalkPreview("${stem}_walk.png", 900, $reach)
    Write-Host "  renders -> $DebugOut, ${stem}_elevation.png, ${stem}_walk.png"
}

# -------------------------------------------------------------- json ----

function S {
    param([string]$Tex, [double]$Tile, [double]$Far, [double]$Tri, [double]$TriFar,
          [double]$Nrm, [double]$NrmFar, [double]$NB, [double]$HB,
          [double[]]$Diff, [double[]]$FarRemap, [double[]]$MMin, [double[]]$MMax)
    $p = "Environment/01_Highlands/Stratum/$Tex"
    [ordered]@{
        name = $null
        albedo = @{ path = "${p}_albedo.tga" }
        normal = @{ path = "${p}_normal.tga" }
        mask   = @{ path = "${p}_mask.tga" }
        tileSize             = @{ x = $Tile; y = $Tile }
        tileSizeFar          = @{ x = $Far;  y = $Far }
        tileSizeTriplanar    = $Tri
        tileSizeFarTriplanar = $TriFar
        normalScale        = $Nrm
        normalScaleFar     = $NrmFar
        normalFarNearBlend = $NB
        heightFarNearBlend = $HB
        diffuseRemap  = @{ r = $Diff[0];     g = $Diff[1];     b = $Diff[2];     a = $Diff[3] }
        farColorRemap = @{ r = $FarRemap[0]; g = $FarRemap[1]; b = $FarRemap[2]; a = $FarRemap[3] }
        maskRemapMin  = @{ x = $MMin[0]; y = $MMin[1]; z = $MMin[2]; w = $MMin[3] }
        maskRemapMax  = @{ x = $MMax[0]; y = $MMax[1]; z = $MMax[2]; w = $MMax[3] }
    }
}

# Drier, rockier palette than Serpent Crossing. All eight verified present in
# both the engine and map-editor packs.
$stratums = @(
    (S 'highlands_100m_sand01'        10 60 12 36 1.0 1.0  0.0   0.5 @(0.42,0.372,0.30,1.0)   @(0.24,0.21,0.16,0.0) @(0,0,0.1,0) @(1,1,0.9,1))
    (S 'highlands_60m_rock_basalt01'  10 44 10 36 1.0 1.0  0.2   0.5 @(0.58,0.556,0.54,1.0)   @(1,1,1,0) @(0,0,0,0) @(1,1,1,1))
    (S 'highlands_100m_heather03'      8 32 12 36 1.0 1.0  0.5   0.5 @(0.298,0.286,0.192,1.0) @(0.0376,0.0347,0.0347,0.0) @(0,0,0,0) @(1,1,1,1))
    # grass03, not grass04: grass04 exists only in the map editor's pack.
    (S 'highlands_100m_grass03'        8 64 12 36 1.0 1.0  0.32  0.5 @(0.44,0.47,0.36,1.0)    @(0.19,0.18,0.13,0.0) @(0,0,0,0) @(1,1,1,1))
    (S 'highlands_50m_heather01'       8 32 12 36 1.0 1.0  0.53  0.5 @(0.40,0.40,0.30,1.0)    @(0.066,0.043,0.022,0.0) @(0,0,0.1,0) @(1,1,0.8,1))
    (S 'highlands_100m_mud01'          8 40 12 36 1.0 1.0  0.57  0.5 @(0.30,0.27,0.23,1.0)    @(1,1,1,0) @(0,0,0,0) @(1,1,1,1))
    (S 'highlands_100m_sand02'        10 32  8 36 0.8 0.8  0.06  0.5 @(0.55,0.47,0.34,1.0)    @(0.25,0.213,0.139,0.0) @(0,0,0,0) @(1,1,1,1))
    (S 'highlands_100m_rock_cliff01'  12 52 10 36 1.0 1.0  0.164 0.5 @(0.6667,0.5373,0.5137,1.0) @(1,1,1,0) @(0,0,0,0) @(1,1,1,1))
    (S 'highlands_60m_gravel01'       12 52 10 36 1.0 1.0  0.164 0.5 @(0.62,0.58,0.53,1.0)    @(1,1,1,0) @(0,0,0,0) @(1,1,1,1))
)

function T {
    param([double]$X, [double]$Y, [double]$Z)
    [ordered]@{
        position = @{ x = $X;  y = $Y;  z = $Z }
        rotation = @{ x = 0.0; y = 0.0; z = 0.0; w = 1.0 }
        scale    = @{ x = 1.0; y = 1.0; z = 1.0 }
    }
}

$spawnT = [ordered]@{}
foreach ($s in $spawns) { $spawnT[$s.Army] = T $s.X ([math]::Round([MapGen]::HeightAtWorld($s.X, $s.Z), 2)) $s.Z }

$alloyT = [ordered]@{}
$i = 0
foreach ($p in $alloyPts) {
    $i++
    $y = [math]::Round([MapGen]::HeightAtWorld($p[0], $p[1]), 2)
    $alloyT["Alloys_{0:D3}" -f $i] = T $p[0] $y $p[1]
}

function Army { [ordered]@{ faction = 0; alloys = 500.0; energy = 500.0; groups = @{} } }

$map = [ordered]@{
    fileVersion         = 3
    mapVersion          = 1
    name                = $MapName
    credits             = ''
    width               = $Size
    length              = $Size
    height              = 128            # SanMap.height is an int
    heightmapResolution = [MapGen]::HRes
    hasWater                   = $false
    waterLevel                 = 0.0
    waterDepth                 = 0.0
    waterWindSpeed             = 0.25
    waterWindDirection         = 160.0
    waterShoreDepthOffset      = 8.0
    waterShoreDepthStrength    = 0.7
    waterShoreDistanceOffset   = 0.0
    waterShoreDistanceStrength = 2.0
    shader              = 'RTS/TerrainLit'
    heightTransition    = 2.0
    fadeDistance        = 60.0
    fadeStartDistance   = 34.0
    stratumLayers       = $stratums

    sunRA                     = 118.0
    sunDA                     = 38.0
    sunIntensity              = 62000.0
    sunTint                   = @{ r = 1.0; g = 0.98; b = 0.94; a = 1.0 }
    sunTemperature            = 7200.0
    sunAngularDiameter        = 0.5
    sunVolumetricsMultiplier  = 6.7
    sunVolumetricsShadowDimer = 0.5
    skylightIntensity         = 0.0
    skylightTint              = @{ r = 1.0; g = 1.0; b = 1.0; a = 1.0 }
    skylightTemperature       = 11000.0
    exposure                  = 11.8
    exposureCompensation      = 0.0
    skyboxExposure            = 12.0
    fogAttenuationDistance    = 420.0
    fogBaseHeight             = 8.0
    fogMaximumHeight          = 150.0
    fogMaximumDistance        = 2200.0
    fogAnisotropy             = 0.3
    skybox = @{ path = 'Environment/Skybox/kloofendal_48d_partly_cloudy_puresky_4k.exr' }

    areas   = @{ Playable = @{ x = 0.0; y = 0.0; width = [double]$Size; height = [double]$Size } }
    armies  = [ordered]@{ ARMY_1 = (Army); ARMY_2 = (Army) }
    chains  = @{}
    markers = [ordered]@{
        Spawn  = [ordered]@{ resource = $false; transforms = $spawnT }
        Alloys = [ordered]@{ resource = $true;  transforms = $alloyT }
    }
    decals = @()
    windSpeed     = 0.3
    windDirection = 120.0
    props         = $propGroups
}

# Fields the shipped maps set that SanMap would otherwise default badly - most
# importantly the height fog. See src\Biomes.ps1.
foreach ($kv in (New-MapEnvironment 'Arid' ([double][MapGen]::WaterLevel)).GetEnumerator()) {
    $map[$kv.Key] = $kv.Value
}
$sanmap = Join-Path $mapDir "$Folder.sanmap"
[IO.File]::WriteAllText($sanmap, ($map | ConvertTo-Json -Depth 12), (New-Object Text.UTF8Encoding $false))

Write-Host ''
Get-ChildItem $mapDir -Recurse -File | ForEach-Object { "  {0,-24} {1,12:N0}" -f $_.Name, $_.Length }
Write-Host ''
& (Join-Path $MapGenTools 'Test-Sanmap.ps1') -Path $sanmap -CheckTextures
Write-Host ''
Write-Host "Open: $sanmap"
