using System.Linq;
using System.Text;

namespace SanctuaryMapConverter.Core
{
    // New-OrganicMap.ps1 in C#: builds "Broken Mesa" - a 1v1, 512 m, dry
    // highland map.
    //
    // Where Serpent Crossing uses analytic plateaus, this thresholds a
    // domain-warped noise field into branching mesas: organic outlines, flat
    // tops, hard cliff edges, and a second tier nested inside the first.
    // Nothing about that construction produces a way up, so CarveRamps finds
    // every stranded region and cuts a constant-gradient corridor down to
    // reachable ground, repeating until the whole map is connected.
    //
    // No river - the barriers here are the cliffs themselves.
    public static partial class NamedMaps
    {
        public static string OrganicMap(string mapsRoot, string propExtension = ".santp",
            Action<string> log = null, ValidateOptions validate = null, string debugOut = null,
            string folder = "Broken_Mesa", string mapName = "Broken Mesa")
        {
            log ??= _ => { };
            EngineState.Reset();   // fresh MapGen statics, like a fresh PS process
            int size = 512;          // the script's -Size default
            int seed = 20250822;     // the script's -Seed default

            string mapDir = Path.Combine(mapsRoot, folder);
            string texDir = Path.Combine(mapDir, "Textures");
            if (Directory.Exists(mapDir)) Directory.Delete(mapDir, true);
            Directory.CreateDirectory(texDir);

            // ------------------------------------------------------------- config ----

            double M = size;
            MapGen.Configure(size, size >= 512 ? 1024 : 512);
            MapGen.UseRiver     = false;
            MapGen.Organic      = false;
            MapGen.OrganicHills = false;
            MapGen.PathedMesas  = true;
            MapGen.LandBase     = 22.0f;
            MapGen.WaterLevel   = 0.0f;      // dry map; nothing sits below this
            MapGen.HillStrength = 1.0f;

            // Nothing but mesa country here, so it wants more landforms than Cleftwater and
            // can afford a smaller centre keep-out with no river splitting the middle.
            MapGen.MesaPathCount   = 8;
            MapGen.MesaMinSep      = 0.155f;
            MapGen.MesaCentreClear = 0.15f;
            MapGen.MesaInflate     = 0.015f;
            MapGen.MesaRampCount   = 7;
            MapGen.MesaRampWidth   = 15.0f;
            MapGen.OutcropHeight   = 0.0f;

            // Spawns on the TL/BR diagonal, pulled in from the corners.
            MapGen.BaseX = new[] { (float)(size * 0.22), (float)(size * 0.78) };
            MapGen.BaseZ = new[] { (float)(size * 0.78), (float)(size * 0.22) };

            log("Building mesa masks (paths -> inflate -> quarter-res -> dilute -> blur -> distance field)...");
            MapGen.BuildMesaField(seed, 15.0f, 10.0f);

            log($"Building heightfield ({size} m, pathed mesas)...");
            MapGen.BuildHeight();

            // ------------------------------------------------------- ramp carving ----

            log("Carving ramps...");
            MapGen.BuildWalkable();
            int before = MapGen.CountTrue(MapGen.Reachable(MapGen.BaseX[0], MapGen.BaseZ[0]));
            int walk0 = MapGen.WalkableCount();
            log(string.Format("  before: {0:P0} of walkable ground reachable from ARMY_1", (double)before / walk0));

            int carved = MapGen.CarveRamps(MapGen.BaseX[0], MapGen.BaseZ[0], 40, 11.0f, 9.0f, 120);
            // Sand off invisible one-cell obstacles: they leave the map 100% reachable
            // but litter it with pinch points units path around.
            int despeckled = MapGen.SmoothPathingSpecks(60, 8);
            log(string.Format("  smoothed {0} isolated blocked patches", despeckled));
            log(string.Format("  cut {0} ramp corridor(s)", carved));

            MapGen.BuildWalkable();
            bool[,] reach = MapGen.Reachable(MapGen.BaseX[0], MapGen.BaseZ[0]);
            int walk = MapGen.WalkableCount();
            int rc = MapGen.CountTrue(reach);
            log(string.Format("  after:  {0:P0} of walkable ground reachable ({1:N0} / {2:N0} cells)",
                (double)rc / walk, rc, walk));

            log("Building stratum weights...");
            MapGen.BuildLayers();
            // Slot badges on the preview, in spawn order.
            MapGen.PreviewSpawnX = (float[])MapGen.BaseX.Clone();
            MapGen.PreviewSpawnZ = (float[])MapGen.BaseZ.Clone();

            // ------------------------------------------------------------ markers ----

            // Nine per side; the mirror set is generated by rotation so the map is fair.
            // Positions are fractions of map size so this scales with the size.
            var alloyFracA = new[]
            {
                new[] { 0.22, 0.90 }, new[] { 0.31, 0.86 }, new[] { 0.14, 0.74 }, new[] { 0.30, 0.70 },
                new[] { 0.44, 0.92 }, new[] { 0.09, 0.55 }, new[] { 0.47, 0.72 }, new[] { 0.62, 0.88 },
                new[] { 0.40, 0.55 },
            };

            var spawns = new (string Army, double X, double Z)[]
            {
                ("ARMY_1", MapGen.BaseX[0], MapGen.BaseZ[0]),
                ("ARMY_2", MapGen.BaseX[1], MapGen.BaseZ[1]),
            };

            bool TestOk(double x, double z, double maxSlope)
            {
                if (x < 10 || x > (M - 10) || z < 10 || z > (M - 10)) return false;
                if (MapGen.SlopeAtWorld((float)x, (float)z) > maxSlope) return false;
                // must also be somewhere units can actually stand
                return MapGen.IsReachable(reach, (float)x, (float)z);
            }

            double[] ResolveSpot(double x, double z, double maxSlope, string label)
            {
                if (TestOk(x, z, maxSlope)) return new[] { x, z };
                foreach (int rad in new[] { 5, 10, 15, 21, 28, 36, 45, 55 })
                {
                    for (int deg = 0; deg <= 23; deg++)
                    {
                        double a = deg * 15 * Math.PI / 180;
                        double nx = Math.Round(x + rad * Math.Cos(a));
                        double nz = Math.Round(z + rad * Math.Sin(a));
                        if (TestOk(nx, nz, maxSlope))
                        {
                            log(string.Format("  nudged {0}: ({1},{2}) -> ({3},{4})  [{5} m]",
                                label, x, z, nx, nz, rad));
                            return new[] { nx, nz };
                        }
                    }
                }
                log($"WARNING: could not place {label} near ({x},{z})");
                return new[] { x, z };
            }

            log("Placing markers...");
            var resolvedA = new List<double[]>();
            int i = 0;
            foreach (var f in alloyFracA)
            {
                i++;
                double fx = f[0];
                double fz = f[1];
                resolvedA.Add(ResolveSpot(fx * M, fz * M, 12.0, string.Format("alloy A{0}", i)));
            }

            var alloyPts = new List<double[]>();
            foreach (var p in resolvedA) alloyPts.Add(new[] { p[0], p[1] });
            foreach (var p in resolvedA)
            {
                double rx = M - p[0];
                double rz = M - p[1];
                alloyPts.Add(new[] { rx, rz });
            }

            // --------------------------------------------------------- validation ---

            log("Pathability (Land layer, maxSlope 30 deg):");
            bool enemyOk = MapGen.IsReachable(reach, MapGen.BaseX[1], MapGen.BaseZ[1]);
            log(string.Format("  enemy spawn reachable overland: {0}", enemyOk ? "YES" : "NO"));
            var bad = new List<string>();
            i = 0;
            foreach (var p in alloyPts)
            {
                i++;
                if (!MapGen.IsReachable(reach, (float)p[0], (float)p[1])) bad.Add(string.Format("Alloys_{0:D3}", i));
            }
            if (bad.Count > 0) log("WARNING: " + string.Format("  cut off: {0}", string.Join(", ", bad)));
            else log(string.Format("  all {0} alloy spots reachable on foot", alloyPts.Count));

            float[] ts = MapGen.TerrainStats();
            float land = ts[2];
            log(string.Format("Terrain: {0:N1} m .. {1:N2} m ({2:N1} m of relief)", ts[0], ts[1], ts[1] - ts[0]));
            log(string.Format("  slopes: {0:P0} flat (<6 deg), {1:P0} gentle (6-15), {2:P0} steep (15-34), {3:P0} cliff (>34)",
                (double)ts[3] / land, (double)ts[4] / land, (double)ts[5] / land, (double)ts[6] / land));
            log("");

            // ---------------------------------------------------------- textures ----

            log("Writing textures...");
            MapGen.WriteHeightmap(Path.Combine(texDir, "heightmap.raw"));
            MapGen.WriteStratums(texDir);
            MapGen.WriteTints(texDir, 2048);
            MapGen.WritePreview(Path.Combine(texDir, "preview.png"), 512, false, null, null, null);
            File.Copy(Path.Combine(texDir, "preview.png"), Path.Combine(mapDir, "preview.png"));

            // -------------------------------------------------------------- props ---

            string[] treeBps = { "edbm0121", "edbm0122", "edbm0123", "edbm0124", "edbm0125" };
            string[] rockBps = { "edmm0104", "edmm0106", "edms0110" };
            float[] avoidX = alloyPts.Select(p => (float)p[0]).ToArray();
            float[] avoidZ = alloyPts.Select(p => (float)p[1]).ToArray();

            log($"Scattering props ({propExtension})...");
            var buckets = new Dictionary<string, List<JObj>>();
            foreach (var b in treeBps.Concat(rockBps)) buckets[b] = new List<JObj>();
            foreach (var (bps, rocks, count, scatterSeed) in new[]
            {
                (treeBps, false, 420, 2207),
                (rockBps, true, 180, 9311),
            })
            {
                float[] flat = MapGen.Scatter(scatterSeed, count, rocks, avoidX, avoidZ, 14.0f);
                int n = flat.Length / 5;
                for (int k = 0; k < n; k++)
                {
                    double x = flat[k * 5], y = flat[k * 5 + 1], z = flat[k * 5 + 2];
                    double yaw = flat[k * 5 + 3], sc = flat[k * 5 + 4];
                    string bp = bps[k % bps.Length];
                    foreach (var inst in new[] { new[] { x, z, yaw }, new[] { M - x, M - z, yaw + Math.PI } })
                    {
                        buckets[bp].Add(Json.Obj(
                            ("position", Json.Vec3(Math.Round(inst[0], 3), Math.Round(y, 3), Math.Round(inst[1], 3))),
                            ("rotation", Json.Quat(0.0, Math.Round(Math.Sin(inst[2] / 2), 7), 0.0, Math.Round(Math.Cos(inst[2] / 2), 7))),
                            ("scale", Json.Vec3(Math.Round(sc, 4), Math.Round(sc, 4), Math.Round(sc, 4)))));
                    }
                }
                log(string.Format("  {0}: {1} per side -> {2} total", rocks ? "rocks" : "trees", n, n * 2));
            }
            var propGroups = new List<JObj>();
            foreach (var b in treeBps.Concat(rockBps))
            {
                if (buckets[b].Count == 0) continue;
                propGroups.Add(Json.Obj(
                    ("blueprintPath", $"Environment/01_Highlands/Props/{b}/{b}{propExtension}"),
                    ("transforms", buckets[b])));
            }

            if (debugOut != null)
            {
                var mx = new List<float>(); var mz = new List<float>(); var mk = new List<int>();
                foreach (var g in propGroups)
                    foreach (var t in (List<JObj>)g.Items[1].Value)      // transforms
                    {
                        var pos = (JObj)t.Items[0].Value;                // position
                        mx.Add((float)(double)pos.Items[0].Value);       // x
                        mz.Add((float)(double)pos.Items[2].Value);       // z
                        mk.Add(2);
                    }
                foreach (var p in alloyPts) { mx.Add((float)p[0]); mz.Add((float)p[1]); mk.Add(1); }
                foreach (var s in spawns) { mx.Add((float)s.X); mz.Add((float)s.Z); mk.Add(0); }
                MapGen.WritePreview(debugOut, 900, true, mx.ToArray(), mz.ToArray(), mk.ToArray());
                string stem = Path.ChangeExtension(debugOut, null).TrimEnd('.');
                MapGen.WriteHeightPreview(stem + "_elevation.png", 900);
                MapGen.WriteWalkPreview(stem + "_walk.png", 900, reach);
                log($"  renders -> {debugOut}, {stem}_elevation.png, {stem}_walk.png");
            }

            // -------------------------------------------------------------- json ----

            static JObj S(string tex, double tile, double far, double tri, double triFar,
                double nrm, double nrmFar, double nb, double hb,
                double[] diff, double[] farRemap, double[] mmin, double[] mmax)
            {
                string p = $"Environment/01_Highlands/Stratum/{tex}";
                return Json.Obj(
                    ("name", null),
                    ("albedo", Json.Obj(("path", p + "_albedo.tga"))),
                    ("normal", Json.Obj(("path", p + "_normal.tga"))),
                    ("mask", Json.Obj(("path", p + "_mask.tga"))),
                    ("tileSize", Json.Obj(("x", tile), ("y", tile))),
                    ("tileSizeFar", Json.Obj(("x", far), ("y", far))),
                    ("tileSizeTriplanar", tri),
                    ("tileSizeFarTriplanar", triFar),
                    ("normalScale", nrm),
                    ("normalScaleFar", nrmFar),
                    ("normalFarNearBlend", nb),
                    ("heightFarNearBlend", hb),
                    ("diffuseRemap", Json.Rgba(diff[0], diff[1], diff[2], diff[3])),
                    ("farColorRemap", Json.Rgba(farRemap[0], farRemap[1], farRemap[2], farRemap[3])),
                    ("maskRemapMin", Json.Quat(mmin[0], mmin[1], mmin[2], mmin[3])),
                    ("maskRemapMax", Json.Quat(mmax[0], mmax[1], mmax[2], mmax[3])));
            }

            // Drier, rockier palette than Serpent Crossing. All eight verified present in
            // both the engine and map-editor packs.
            var stratums = new List<JObj>
            {
                S("highlands_100m_sand01",       10, 60, 12, 36, 1.0, 1.0, 0.0,   0.5,
                    new double[] { 0.42, 0.372, 0.30, 1.0 },   new double[] { 0.24, 0.21, 0.16, 0.0 },
                    new double[] { 0, 0, 0.1, 0 }, new double[] { 1, 1, 0.9, 1 }),
                S("highlands_60m_rock_basalt01", 10, 44, 10, 36, 1.0, 1.0, 0.2,   0.5,
                    new double[] { 0.58, 0.556, 0.54, 1.0 },   new double[] { 1, 1, 1, 0 },
                    new double[] { 0, 0, 0, 0 },   new double[] { 1, 1, 1, 1 }),
                S("highlands_100m_heather03",     8, 32, 12, 36, 1.0, 1.0, 0.5,   0.5,
                    new double[] { 0.298, 0.286, 0.192, 1.0 }, new double[] { 0.0376, 0.0347, 0.0347, 0.0 },
                    new double[] { 0, 0, 0, 0 },   new double[] { 1, 1, 1, 1 }),
                // grass03, not grass04: grass04 exists only in the map editor's pack.
                S("highlands_100m_grass03",       8, 64, 12, 36, 1.0, 1.0, 0.32,  0.5,
                    new double[] { 0.44, 0.47, 0.36, 1.0 },    new double[] { 0.19, 0.18, 0.13, 0.0 },
                    new double[] { 0, 0, 0, 0 },   new double[] { 1, 1, 1, 1 }),
                S("highlands_50m_heather01",      8, 32, 12, 36, 1.0, 1.0, 0.53,  0.5,
                    new double[] { 0.40, 0.40, 0.30, 1.0 },    new double[] { 0.066, 0.043, 0.022, 0.0 },
                    new double[] { 0, 0, 0.1, 0 }, new double[] { 1, 1, 0.8, 1 }),
                S("highlands_100m_mud01",         8, 40, 12, 36, 1.0, 1.0, 0.57,  0.5,
                    new double[] { 0.30, 0.27, 0.23, 1.0 },    new double[] { 1, 1, 1, 0 },
                    new double[] { 0, 0, 0, 0 },   new double[] { 1, 1, 1, 1 }),
                S("highlands_100m_sand02",       10, 32,  8, 36, 0.8, 0.8, 0.06,  0.5,
                    new double[] { 0.55, 0.47, 0.34, 1.0 },    new double[] { 0.25, 0.213, 0.139, 0.0 },
                    new double[] { 0, 0, 0, 0 },   new double[] { 1, 1, 1, 1 }),
                S("highlands_100m_rock_cliff01", 12, 52, 10, 36, 1.0, 1.0, 0.164, 0.5,
                    new double[] { 0.6667, 0.5373, 0.5137, 1.0 }, new double[] { 1, 1, 1, 0 },
                    new double[] { 0, 0, 0, 0 },   new double[] { 1, 1, 1, 1 }),
                S("highlands_60m_gravel01",      12, 52, 10, 36, 1.0, 1.0, 0.164, 0.5,
                    new double[] { 0.62, 0.58, 0.53, 1.0 },    new double[] { 1, 1, 1, 0 },
                    new double[] { 0, 0, 0, 0 },   new double[] { 1, 1, 1, 1 }),
            };

            static JObj T(double x, double y, double z) => Json.Obj(
                ("position", Json.Vec3(x, y, z)),
                ("rotation", Json.Quat(0.0, 0.0, 0.0, 1.0)),
                ("scale", Json.Vec3(1.0, 1.0, 1.0)));

            var spawnT = new JObj();
            foreach (var s in spawns)
                spawnT.Add(s.Army, T(s.X, Math.Round(MapGen.HeightAtWorld((float)s.X, (float)s.Z), 2), s.Z));

            var alloyT = new JObj();
            i = 0;
            foreach (var p in alloyPts)
            {
                i++;
                double y = Math.Round(MapGen.HeightAtWorld((float)p[0], (float)p[1]), 2);
                alloyT.Add(string.Format("Alloys_{0:D3}", i), T(p[0], y, p[1]));
            }

            static JObj Army() => Json.Obj(
                ("faction", 0), ("alloys", 500.0), ("energy", 500.0), ("groups", Json.Obj()));

            var map = Json.Obj(
                ("fileVersion", 3),
                ("mapVersion", 1),
                ("name", mapName),
                ("credits", ""),
                ("width", size),
                ("length", size),
                ("height", 128),                       // SanMap.height is an int
                ("heightmapResolution", MapGen.HRes),
                ("hasWater", false),
                ("waterLevel", 0.0),
                ("waterDepth", 0.0),
                ("waterWindSpeed", 0.25),
                ("waterWindDirection", 160.0),
                ("waterShoreDepthOffset", 8.0),
                ("waterShoreDepthStrength", 0.7),
                ("waterShoreDistanceOffset", 0.0),
                ("waterShoreDistanceStrength", 2.0),
                ("shader", "RTS/TerrainLit"),
                ("heightTransition", 2.0),
                ("fadeDistance", 60.0),
                ("fadeStartDistance", 34.0),
                ("stratumLayers", stratums),

                ("sunRA", 118.0),
                ("sunDA", 38.0),
                ("sunIntensity", 62000.0),
                ("sunTint", Json.Rgba(1.0, 0.98, 0.94, 1.0)),
                ("sunTemperature", 7200.0),
                ("sunAngularDiameter", 0.5),
                ("sunVolumetricsMultiplier", 6.7),
                ("sunVolumetricsShadowDimer", 0.5),
                ("skylightIntensity", 0.0),
                ("skylightTint", Json.Rgba(1.0, 1.0, 1.0, 1.0)),
                ("skylightTemperature", 11000.0),
                ("exposure", 11.8),
                ("exposureCompensation", 0.0),
                ("skyboxExposure", 12.0),
                ("fogAttenuationDistance", 420.0),
                ("fogBaseHeight", 8.0),
                ("fogMaximumHeight", 150.0),
                ("fogMaximumDistance", 2200.0),
                ("fogAnisotropy", 0.3),
                ("skybox", Json.Obj(("path", "Environment/Skybox/kloofendal_48d_partly_cloudy_puresky_4k.exr"))),

                ("areas", Json.Obj(("Playable", Json.Obj(
                    ("x", 0.0), ("y", 0.0), ("width", (double)size), ("height", (double)size))))),
                ("armies", Json.Obj(("ARMY_1", Army()), ("ARMY_2", Army()))),
                ("chains", Json.Obj()),
                ("markers", Json.Obj(
                    ("Spawn", Json.Obj(("resource", false), ("transforms", spawnT))),
                    ("Alloys", Json.Obj(("resource", true), ("transforms", alloyT))))),
                ("decals", new List<JObj>()),
                ("windSpeed", 0.3),
                ("windDirection", 120.0),
                ("props", propGroups));

            // Fields the shipped maps set that SanMap would otherwise default badly - most
            // importantly the height fog. (The PS script merged New-MapEnvironment 'Arid'.)
            Biome.AddEnvironment(map, MapGen.WaterLevel);

            string sanmap = Path.Combine(mapDir, folder + ".sanmap");
            File.WriteAllText(sanmap, Json.Write(map), new UTF8Encoding(false));

            log("");
            foreach (var f in new DirectoryInfo(mapDir).EnumerateFiles("*", SearchOption.AllDirectories))
                log(string.Format("  {0,-24} {1,12:N0}", f.Name, f.Length));
            log("");
            // The PS script ran tools\Test-Sanmap.ps1 -Path <sanmap> -CheckTextures here.
            if (validate != null) Validator.Check(sanmap, validate, log);
            log("");
            log($"Open: {sanmap}");
            return mapDir;
        }
    }
}
